#ifndef TOY_KERNEL_INCLUDE_SYS_MMAN_H
#define TOY_KERNEL_INCLUDE_SYS_MMAN_H

#define MAP_FAILED ((void *)(-1))
#define MAP_FILE 0x00
#define MAP_SHARED 0x01
#define MAP_PRIVATE 0x02
#define MAP_FIXED 0x10
#define MAP_ANON 0x20
#define MAP_ANONYMOUS 0x20
#define MAP_NORESERVE 0x4000

#endif  // TOY_KERNEL_INCLUDE_SYS_MMAN_H